Server:
  port: 8080
RestApi:
  kakao:
    host: "https://dapi.kakao.com/"
    path: "/v2/search/blog"
    key: "KakaoAK e6cf760ee93f406c3e67cce178ae9960"
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      web-allow-others: true
  profiles:
      active: local
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace

